server:
  port: ${port:9910} #服务端口

spring:
  application:
    name: spring-config-line  #指定本项目服务名
  cloud:
    config:
      server:
        git: #配置git仓库地址
          uri: ${gitUrl:https://github.com/18321473057/spring-config-repostory-line.git}
          #username: XXX
          #password: XXX
          default-label: master #配置文件分支
          search-paths: repostory  #配置文件所在根目录

  rabbitmq: #RabbitMQ相关的配置
    host: 192.168.99.129
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://ycs:1234@192.168.99.129:9900/eureka/
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ipAddress: ${ipAddress:127.0.0.1}

management:
  security:
    enabled: false #是否开启actuator安全认证